const https = require('https');
const http = require('http');

// ============================================================
// HUMANIZER ENGINE
// Pluggable LLM + AI detection verification loop
// ============================================================

const SYSTEM_PROMPT = `You are a text rewriter. Your job is to rewrite AI-generated text so it reads like a real human wrote it — someone who writes well but naturally, not perfectly.

RULES:
1. VARY SENTENCE LENGTH DRAMATICALLY. Mix very short sentences (3-5 words) with longer complex ones. Humans are erratic writers.
2. Use imperfect transitions. "Anyway," "So," "The thing is," "Look," "Right?" — not every paragraph needs a smooth bridge.
3. BREAK parallel structure. If three points in a row follow the same pattern, restructure at least one differently.
4. Add parenthetical asides (like this one) occasionally — humans think out loud.
5. Start some sentences with "And" or "But." English teachers hate it. Real writers do it constantly.
6. Mix registers within paragraphs — a technical sentence followed by something casual is very human.
7. Use contractions inconsistently. Sometimes "don't", sometimes "do not." Humans aren't consistent about this.
8. Occasionally use em dashes — like this — instead of always using commas or parentheses.
9. Don't hedge everything. Humans commit to statements. Say "it's faster" not "it tends to be faster in most scenarios."
10. Preserve the EXACT meaning, technical accuracy, all links, all formatting, and all code blocks unchanged.
11. Do NOT add fluff, do NOT make it longer, do NOT add motivational language.
12. Do NOT use these AI-typical phrases: "In this article", "Let's dive in", "It's worth noting", "In today's world", "game-changer", "landscape", "leverage", "comprehensive", "streamline", "robust", "cutting-edge", "delve".
13. Keep the author's voice and personality intact. You're adjusting HOW it's written, not WHAT it says.
14. CODE BLOCKS must be returned EXACTLY as-is. Do not modify any code.

Output ONLY the rewritten text. No explanations, no preamble.`;

const REWRITE_FLAGGED_PROMPT = `The following sentences were flagged as AI-generated by a detector. Rewrite ONLY these sentences to sound more naturally human. Return the full text with just these sentences changed.

Flagged sentences:
{flagged}

Full text:
{text}

Rewrite the flagged sentences to be less predictable — vary word choice, sentence structure, add slight imperfections. Output the full text with changes applied.`;

// ============================================================
// LLM PROVIDERS
// ============================================================

class LLMProvider {
  constructor(config) {
    this.provider = config.provider || 'openai';
    this.apiKey = config.apiKey;
    this.model = config.model;
    this.baseUrl = config.baseUrl;

    // Defaults per provider
    if (this.provider === 'openai') {
      this.model = this.model || 'gpt-4o-mini';
      this.baseUrl = this.baseUrl || 'https://api.openai.com';
    } else if (this.provider === 'anthropic') {
      this.model = this.model || 'claude-sonnet-4-20250514';
      this.baseUrl = this.baseUrl || 'https://api.anthropic.com';
    } else if (this.provider === 'custom') {
      // OpenAI-compatible endpoint
      if (!this.baseUrl) throw new Error('baseUrl required for custom provider');
      this.model = this.model || 'default';
    }
  }

  async complete(systemPrompt, userPrompt) {
    if (this.provider === 'anthropic') {
      return this._anthropic(systemPrompt, userPrompt);
    }
    // OpenAI and custom both use OpenAI format
    return this._openai(systemPrompt, userPrompt);
  }

  _openai(systemPrompt, userPrompt) {
    const body = JSON.stringify({
      model: this.model,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      temperature: 0.8,
      max_tokens: 4096,
    });

    const url = new URL(this.baseUrl + '/v1/chat/completions');
    return this._request(url, body, {
      'Authorization': `Bearer ${this.apiKey}`,
      'Content-Type': 'application/json',
    }).then(data => {
      const parsed = JSON.parse(data);
      return parsed.choices?.[0]?.message?.content || '';
    });
  }

  _anthropic(systemPrompt, userPrompt) {
    const body = JSON.stringify({
      model: this.model,
      max_tokens: 4096,
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
      temperature: 0.8,
    });

    const url = new URL('https://api.anthropic.com/v1/messages');
    return this._request(url, body, {
      'x-api-key': this.apiKey,
      'anthropic-version': '2023-06-01',
      'Content-Type': 'application/json',
    }).then(data => {
      const parsed = JSON.parse(data);
      return parsed.content?.[0]?.text || '';
    });
  }

  _request(url, body, headers) {
    return new Promise((resolve, reject) => {
      const mod = url.protocol === 'https:' ? https : http;
      const req = mod.request(url, {
        method: 'POST',
        headers: { ...headers, 'Content-Length': Buffer.byteLength(body) },
        timeout: 120000,
      }, res => {
        let data = '';
        res.on('data', c => data += c);
        res.on('end', () => {
          if (res.statusCode >= 400) {
            reject(new Error(`LLM API error ${res.statusCode}: ${data.slice(0, 500)}`));
          } else {
            resolve(data);
          }
        });
      });
      req.on('error', reject);
      req.on('timeout', () => { req.destroy(); reject(new Error('LLM request timeout')); });
      req.write(body);
      req.end();
    });
  }
}

// ============================================================
// AI DETECTION (GPTZero)
// ============================================================

class AIDetector {
  constructor(apiKey) {
    this.apiKey = apiKey;
  }

  async detect(text) {
    if (!this.apiKey) {
      // No detector configured — skip verification
      return { score: 0, human_score: 1, sentences: [], skipped: true };
    }

    const body = JSON.stringify({ document: text });
    const url = new URL('https://api.gptzero.me/v2/predict/text');

    return new Promise((resolve, reject) => {
      const req = https.request(url, {
        method: 'POST',
        headers: {
          'x-api-key': this.apiKey,
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(body),
        },
        timeout: 30000,
      }, res => {
        let data = '';
        res.on('data', c => data += c);
        res.on('end', () => {
          try {
            const parsed = JSON.parse(data);
            const doc = parsed.documents?.[0] || {};
            resolve({
              score: doc.completely_generated_prob || 0,
              human_score: 1 - (doc.completely_generated_prob || 0),
              average_perplexity: doc.average_generated_prob || 0,
              sentences: (doc.sentences || [])
                .filter(s => s.generated_prob > 0.7)
                .map(s => ({ text: s.sentence, prob: s.generated_prob })),
            });
          } catch (e) {
            reject(new Error('Detection parse error: ' + e.message));
          }
        });
      });
      req.on('error', reject);
      req.on('timeout', () => { req.destroy(); reject(new Error('Detection timeout')); });
      req.write(body);
      req.end();
    });
  }
}

// ============================================================
// TEXT CHUNKING
// ============================================================

function chunkText(text, maxChunk = 3000) {
  const lines = text.split('\n');
  const chunks = [];
  let current = '';
  let inCodeBlock = false;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('```')) {
      inCodeBlock = !inCodeBlock;
      if (current.trim()) {
        chunks.push({ text: current.trim(), type: 'prose' });
        current = '';
      }
      if (!chunks.length || chunks[chunks.length - 1].type !== 'code') {
        chunks.push({ text: line, type: 'code' });
      } else {
        chunks[chunks.length - 1].text += '\n' + line;
      }
      continue;
    }

    if (inCodeBlock) {
      if (chunks.length && chunks[chunks.length - 1].type === 'code') {
        chunks[chunks.length - 1].text += '\n' + line;
      } else {
        chunks.push({ text: line, type: 'code' });
      }
      continue;
    }

    // Tables pass through unchanged
    if (trimmed.startsWith('|')) {
      if (current.trim() && !current.trim().endsWith('|')) {
        chunks.push({ text: current.trim(), type: 'prose' });
        current = '';
      }
      if (!chunks.length || chunks[chunks.length - 1].type !== 'table') {
        chunks.push({ text: line, type: 'table' });
      } else {
        chunks[chunks.length - 1].text += '\n' + line;
      }
      continue;
    }

    if (current.length + line.length + 1 > maxChunk && current.trim()) {
      chunks.push({ text: current.trim(), type: 'prose' });
      current = '';
    }
    current += line + '\n';
  }
  if (current.trim()) {
    chunks.push({ text: current.trim(), type: 'prose' });
  }
  return chunks;
}

// ============================================================
// MAIN HUMANIZE FUNCTION
// ============================================================

async function humanize(text, options = {}) {
  const llm = new LLMProvider({
    provider: options.llm_provider || 'openai',
    apiKey: options.llm_api_key,
    model: options.llm_model,
    baseUrl: options.llm_base_url,
  });

  const detector = new AIDetector(options.detector_api_key);
  const maxRetries = options.max_retries ?? 2;
  const targetScore = options.target_score ?? 0.3; // below 0.3 = likely human

  const chunks = chunkText(text, options.max_chunk_size || 3000);
  const results = [];
  const log = [];

  for (let i = 0; i < chunks.length; i++) {
    const chunk = chunks[i];

    if (chunk.type !== 'prose') {
      // Code blocks and tables pass through unchanged
      results.push(chunk.text);
      log.push({ chunk: i + 1, type: chunk.type, action: 'passthrough' });
      continue;
    }

    log.push({ chunk: i + 1, type: 'prose', chars: chunk.text.length });

    // Step 1: Initial humanize pass
    let humanized = await llm.complete(SYSTEM_PROMPT, chunk.text);
    log.push({ chunk: i + 1, action: 'initial_rewrite', output_chars: humanized.length });

    // Step 2: Detection loop
    for (let retry = 0; retry <= maxRetries; retry++) {
      const detection = await detector.detect(humanized);

      if (detection.skipped) {
        log.push({ chunk: i + 1, action: 'detection_skipped' });
        break;
      }

      log.push({
        chunk: i + 1,
        retry,
        ai_score: detection.score,
        human_score: detection.human_score,
        flagged_sentences: detection.sentences.length,
      });

      if (detection.score <= targetScore) {
        log.push({ chunk: i + 1, action: 'passed', score: detection.score });
        break;
      }

      if (retry === maxRetries) {
        log.push({ chunk: i + 1, action: 'max_retries_reached', final_score: detection.score });
        break;
      }

      // Step 3: Targeted rewrite of flagged sentences
      if (detection.sentences.length > 0) {
        const flaggedList = detection.sentences.map(s => `- "${s.text}" (${(s.prob * 100).toFixed(0)}% AI)`).join('\n');
        const prompt = REWRITE_FLAGGED_PROMPT
          .replace('{flagged}', flaggedList)
          .replace('{text}', humanized);
        humanized = await llm.complete(SYSTEM_PROMPT, prompt);
        log.push({ chunk: i + 1, action: 'targeted_rewrite', flagged: detection.sentences.length });
      } else {
        // No specific sentences flagged — full rewrite with higher temperature
        humanized = await llm.complete(SYSTEM_PROMPT, 'Rewrite this to sound MORE human and less predictable:\n\n' + humanized);
        log.push({ chunk: i + 1, action: 'full_rewrite' });
      }
    }

    results.push(humanized);
  }

  const output = results.join('\n\n');

  // Final detection on full text if detector is configured
  let finalDetection = null;
  if (options.detector_api_key) {
    try {
      // Only detect on prose portions
      const proseOnly = results.filter((_, i) => chunks[i].type === 'prose').join('\n\n');
      finalDetection = await detector.detect(proseOnly);
    } catch (e) {
      finalDetection = { error: e.message };
    }
  }

  return {
    humanized: output,
    chunks: chunks.length,
    detection: finalDetection,
    log,
  };
}

// ============================================================
// DETECT-ONLY FUNCTION
// ============================================================

async function detectOnly(text, apiKey) {
  const detector = new AIDetector(apiKey);
  return detector.detect(text);
}

module.exports = { humanize, detectOnly, chunkText, LLMProvider, AIDetector };
